swagger: '2.0'

info:
  version: "0.0.1"
  title: DocRaptor v1

host: localhost:3000
basePath: /
schemes: [http]
securityDefinitions:
 basicAuth:
  type: basic
  description: HTTP Basic Authentication. Works over `HTTP` and `HTTPS`
produces:
  - application/pdf
  - application/vnd.ms-excel
  - application/vnd.openxmlformats-officedocument.spreadsheetml.sheet

paths:
  /docs:
    post:
      description: |
        Creates a document synchronously.
      security:
        - basicAuth: []
      parameters:
        - name: doc
          in: body
          description: blah
          required: true
          schema: # json in the body requires schema
            $ref: '#/definitions/Doc'
      responses:
        200:
          description: Successful response
          schema:
            type: file
  /async_docs:
    post:
      description: |
        Creates a document asynchronously.
      security:
        - basicAuth: []
      parameters:
        - name: doc
          in: body
          description: blah
          required: true
          schema: # json in the body requires schema
            $ref: '#/definitions/Doc'
      responses:
        200:
          description: Successful response
          schema:
            $ref: '#/definitions/AsyncDoc'

  /status/{id}:
    get:
      description: |
        WTF IS GOING ON WITH THAT THING THAT I SENT YOU BEFORE?
      security:
        - basicAuth: []
      parameters:
        - name: id
          in: path
          description: blah
          required: true
          schema: # json in the body requires schema
            $ref: '#/definitions/AsyncDocStatus'
      responses:
        200:
          description: Successful response
          schema:
            $ref: '#/definitions/AsyncDocStatus'

  /download/{id}:
    get:
      description: |
        Downloads a document.
      security:
        - basicAuth: []
      parameters:
        - name: id
          in: path
          description: blah
          required: true
      responses:
        200:
          description: Successful response
          schema:
            type: file

definitions:
  Doc:
    type: object
    required:
      - name
      - document_type
      - document_content
    properties:
      name:
        type: string
      document_type:
        type: string
      document_content:
        type: string
      document_url:
        type: string
      test:
        type: boolean
        default: true

        strict:
        tag:
        javascript:

        prince_options:

  AsyncDoc:
    type: object
    properties:
      status_id:
        type: string

  AsyncDocStatus:
    type: object
    properties:
      status:
        type: string
      download_url:
        type: string
      message:
        type: string
      number_of_pages:
        type: integer
      validation_errors:
        type: string

