swagger: '2.0'

info:
  version: "0.0.1"
  title: DocRaptor v1

host: localhost:3000
basePath: /
schemes: [http]
securityDefinitions:
 basicAuth:
  type: basic
  description: HTTP Basic Authentication. Works over `HTTP` and `HTTPS`
produces:
  - application/pdf

paths:
  /docs:
    post:
      description: |
        Creates a document synchronously.
      security:
        - basicAuth: []
      parameters:
        - name: doc
          in: body
          description: blah
          required: true
          schema: # json in the body requires schema
            $ref: '#/definitions/Doc'
      responses:
        200:
          description: Successful response
          schema:
            type: file

definitions:
  Doc:
    type: object
    required:
      - name
      - document_type
      - document_content
    properties:
      name:
        type: string
      document_type:
        type: string
      document_content:
        type: string
      document_url:
        type: string
      test:
        type: boolean
        default: true
