# Example YAML to get you started quickly.
# Be aware that YAML has indentation based scoping.
# Code completion support is available so start typing for available options.
swagger: '2.0'

# This is your document metadata
info:
  version: "0.0.1"
  title: DocRaptor v1

host: smoke.docraptor.com
basePath: /
schemes: [https]
# Describe your paths here
securityDefinitions:
 basicAuth:
  type: basic
  description: HTTP Basic Authentication. Works over `HTTP` and `HTTPS`
produces:
  - application/pdf

paths:
  # This is a path endpoint. Change it.
  /docs:
    # This is a HTTP operation
    post:
      # Describe this verb here. Note: you can use markdown
      description: |
        Creates a document synchronously.
      security:
        - basicAuth: []

      parameters:
        # An example parameter that is in query and is requiredasdf
        - name: user_credentials
          in: query
          description: Your API key.
          required: false
          type: string
          default: YOUR_API_KEY_HERE
        - name: doc
          in: body
          description: blah
          required: true
          schema:
            $ref: '#/definitions/NewDoc'



      # Expected responses for this operation:
      responses:
        # Response code
        200:
          description: Successful response
          # A schema describing your response object.
          # Use JSON Schema format
          
          schema:
            type: file

definitions:
  Doc:
    type: object
    required:
      - name
      - document_type
      - document_content
    properties:
      name:
        type: string
      document_type:
        type: string
      document_content:
        type: string
      document_url:
        type: string
      test:
        type: boolean
        default: true

  NewDoc:
    type: object
    required:
      - doc
    properties:
      doc:
        $ref: '#/definitions/Doc' 