swagger: '2.0'

info:
  version: "0.0.1"
  title: DocRaptor v1

host: localhost:3000
basePath: /
schemes: [http]
securityDefinitions:
 basicAuth:
  type: basic
  description: HTTP Basic Authentication. Works over `HTTP` and `HTTPS`
produces:
  - application/json
  - application/xml
  - application/pdf
  - application/vnd.ms-excel
  - application/vnd.openxmlformats-officedocument.spreadsheetml.sheet

paths:
  /docs:
    post:
      tags: [Client]
      description: |
        Creates a document synchronously.
      security:
        - basicAuth: []
      parameters:
        - name: doc
          in: body
          description: blah
          required: true
          schema: # json in the body requires schema
            $ref: '#/definitions/Doc'
      responses:
        200:
          description: Successful response
          schema:
            type: file
        401:
          description: Unauthorized
        422:
          description: Unprocessable Entity
  /async_docs:
    post:
      tags: [Client]
      description: |
        Creates a document asynchronously.
      security:
        - basicAuth: []
      parameters:
        - name: doc
          in: body
          description: blah
          required: true
          schema: # json in the body requires schema
            $ref: '#/definitions/Doc'
      responses:
        200:
          description: Successful response
          schema:
            $ref: '#/definitions/AsyncDoc'

  /status/{id}:
    get:
      tags: [Client]
      description: |
        WTF IS GOING ON WITH THAT THING THAT I SENT YOU BEFORE?
      security:
        - basicAuth: []
      parameters:
        - name: id
          in: path
          description: blah
          required: true
          schema: # json in the body requires schema
            $ref: '#/definitions/AsyncDocStatus'
      responses:
        200:
          description: Successful response
          schema:
            $ref: '#/definitions/AsyncDocStatus'

  /download/{id}:
    get:
      tags: [Client]
      description: |
        Downloads a document.
      security:
        - basicAuth: []
      parameters:
        - name: id
          in: path
          description: blah
          required: true
      responses:
        200:
          description: Successful response
          schema:
            type: file

definitions:
  Doc:
    type: object
    required:
      - name
      - document_type
      - document_content
    properties:
      name:
        type: string
      document_type:
        type: string
      document_content:
        type: string
      document_url:
        type: string
      test:
        type: boolean
        default: true
      strict:
        type: string
        default: none
        enum:
          - none
          - true
      tag:
        type: string
      help:
        type: boolean
        default: false
      javascript:
        type: boolean
        default: false
      referrer:
        type: string
      prince_options:
        $ref: '#/definitions/PrinceOptions'

  PrinceOptions:
    type: object
    properties:
      baseurl:
        type: string
      no_xinclude:
        type: boolean
      no_network:
        type: boolean
      http_user:
        type: string
      http_password:
        type: string
      http_proxy:
        type: string
      http_timeout:
        type: integer
        # default: 10
      insecure:
        type: boolean
        # default: false
      media:
        type: string
        # default: print
      no_author_style:
        type: boolean
      no_default_style:
        type: boolean
      no_embed_fonts:
        type: boolean
      no_subset_fonts:
        type: boolean
      no_compress:
        type: boolean
      encrypt:
        type: boolean
      key_bits:
        type: integer
        enum:
          - 40
          - 128
      user_password:
        type: string
      owner_password:
        type: string
      disallow_print:
        type: boolean
      disallow_copy:
        type: boolean
      disallow_annotate:
        type: boolean
      disallow_modify:
        type: boolean
      input:
        type: string
        # default: html
        enum:
          - html
          - xml
          - auto
      version:
        type: string
        # default: 10
        # disabled because Java will try to make an enum as 7_1 which fails
        # enum:
        #   - 7.1
        #   - 8.1
        #   - 9.0
        #   - 10
      javascript:
        type: boolean
      css_dpi:
        type: integer
        # default: 96
      profile:
        type: string
        # disabled because Java will try to make an enum with PDF/A-1b which fails
        # enum:
        #   - PDF/A-1b
        #   - PDF/X-3:2003
        #   - PDF/X-4

  AsyncDoc:
    type: object
    properties:
      status_id:
        type: string

  AsyncDocStatus:
    type: object
    properties:
      status:
        type: string
      download_url:
        type: string
      message:
        type: string
      number_of_pages:
        type: integer
      validation_errors:
        type: string
