#!/bin/sh
set -e
cd "`dirname \"$0\"`/.."

echo "=========== generating csharp source"
./script/generate_language csharp

echo "=========== compiling docraptor.dll"
cd clients/csharp
mcs -reference:bin/Newtonsoft.Json.dll,bin/RestSharp.dll,System.Runtime.Serialization.dll -target:library -out:./bin/docraptor.dll -recurse:./src/*.cs
rm ../../test/csharp/*.dll
cp bin/*.dll ../../test/csharp

echo "============== running tests"
cd ../../test/csharp
mcs -reference:Newtonsoft.Json.dll,RestSharp.dll,System.Runtime.Serialization.dll,docraptor.dll basic.cs

mono basic.exe
