#!/bin/sh
set -ex
cd "`dirname \"$0\"`/.."

LIB_PATH="clients/csharp"
SRC_PATH="clients/csharp/src"
MINIMAL_DOCRAPTOR_LIB="$LIB_PATH/docraptor-minimal.dll"
EVERYTHING_DOCRAPTOR_LIB="$LIB_PATH/docraptor-all.dll"

TEST_PATH="test/csharp"

./script/generate_language csharp

mcs -lib:$LIB_PATH/bin -reference:Newtonsoft.Json.dll,RestSharp.dll,System.Runtime.Serialization.dll -target:library -out:$MINIMAL_DOCRAPTOR_LIB -recurse:$SRC_PATH/*.cs

mono test/csharp/ILRepack.exe /internalize /out:$EVERYTHING_DOCRAPTOR_LIB $MINIMAL_DOCRAPTOR_LIB $LIB_PATH/bin/*.dll

mcs -lib:$LIB_PATH -reference:docraptor-all.dll $TEST_PATH/basic.cs -out:$TEST_PATH/basic.exe

cp $EVERYTHING_DOCRAPTOR_LIB $TEST_PATH
mono $TEST_PATH/basic.exe
