#!/bin/sh
set -e
cd "`dirname \"$0\"`/.."

LANGUAGE="$1"
CONFIG_FILE="config.$LANGUAGE.json"
CLIENT_DIRECTORY="clients/$LANGUAGE"

rm -rf $CLIENT_DIRECTORY
mkdir -p $CLIENT_DIRECTORY

if [ ! -f "$CONFIG_FILE" ]; then
  echo "Could not find $CONFIG_FILE"
  ./script/swagger config-help -l $LANGUAGE
  exit 1
fi

./script/swagger generate -t swagger-codegen/modules/swagger-codegen/src/main/resources/$LANGUAGE -c $CONFIG_FILE -i docraptor.yaml -l $LANGUAGE -o CLIENT_DIRECTORY
