#!/bin/sh

SCRIPT="$0"

while [ -h "$SCRIPT" ] ; do
  ls=`ls -ld "$SCRIPT"`
  link=`expr "$ls" : '.*-> \(.*\)$'`
  if expr "$link" : '/.*' > /dev/null; then
    SCRIPT="$link"
  else
    SCRIPT=`dirname "$SCRIPT"`/"$link"
  fi
done

if [ ! -d "${APP_DIR}" ]; then
  APP_DIR=`dirname "$SCRIPT"`/..
  APP_DIR=`cd "${APP_DIR}"; pwd`
fi

executable="./swagger-codegen/modules/swagger-codegen-cli/target/swagger-codegen-cli.jar"

if [ ! -f "$executable" ]
then
  mvn clean package
fi

# if you've executed sbt assembly previously it will use that instead.
export JAVA_OPTS="${JAVA_OPTS} -XX:MaxPermSize=256M -Xmx1024M -DloggerPath=conf/log4j.properties"
ags="$@ generate -t swagger-codegen/modules/swagger-codegen/src/main/resources/java -c config.java.json -i docraptor.yaml -l java -o output/java"

rm -rf output/java
mkdir -p output/java

java $JAVA_OPTS -jar $executable $ags

cd output/java
mvn package


cd ../../test/java
echo "compiling test class..."
javac -classpath .:"../../output/java/target/swagger-java-client-1.0.0.jar" basic.java
echo "running tests"
java -classpath .:"../../output/java/target/swagger-java-client-1.0.0.jar":"../../output/java/target/lib/*" Basic
