#!/bin/sh
set -e
cd "`dirname \"$0\"`/.."

rm -rf output/java
mkdir -p output/java

./script/swagger generate -t swagger-codegen/modules/swagger-codegen/src/main/resources/java -c config.java.json -i docraptor.yaml -l java -o output/java

cd output/java
mvn package

cd ../../test/java
echo "compiling test class..."
javac -classpath .:"../../output/java/target/swagger-java-client-1.0.0.jar" basic.java
echo "running tests"
java -classpath .:"../../output/java/target/swagger-java-client-1.0.0.jar":"../../output/java/target/lib/*" Basic
