#!/bin/sh
set -e
cd "`dirname \"$0\"`/.."

./script/generate_language java

cd output/java
mvn package

cd ../../test/java
echo "compiling test class..."
javac -classpath .:"../../output/java/target/swagger-java-client-1.0.0.jar" basic.java
echo "running tests"
java -classpath .:"../../output/java/target/swagger-java-client-1.0.0.jar":"../../output/java/target/lib/*" Basic
