#!/bin/sh
set -e
cd "`dirname \"$0\"`/.."

# ./script/generate_language node


# The way npm works these will get installed in ./node_modules alongside swagger-js-codegen.
# This is a little weird, but it'll change when we make an npm package with these as dependencies.
npm list request || npm install request
npm list q || npm install q


mkdir -p clients/node

ruby script/yaml_to_json.rb docraptor.yaml clients/node/docraptor.json

node script/node.js > clients/node/docraptor.js

# ghetto monkey patch the client to return binary from the postDocs request
cat clients/node/docraptor.js | sed -e "s/method: 'POST',/method: 'POST', encoding: null,/g" > clients/node/docraptor.js.tmp
mv clients/node/docraptor.js.tmp clients/node/docraptor.js


cd test/node
node basic.js
