#!/bin/sh
set -e
cd "`dirname \"$0\"`/.."

./script/generate_language python

cd test/python
rm -rf venv
which virutualenv || pip install virtualenv
virtualenv venv
source venv/bin/activate
pip install ../../clients/python/
python basic.py
