#!/bin/bash
set -e
cd "`dirname \"$0\"`/.."

rm -rf ./output/ # clean-up previous generated client directory
./script/swagger


# for node
(cd test/node && npm install swagger-js-codegen)


echo "****************************************************************"
echo "*                                                              *"
echo "*                         Good to go!                          *"
echo "*                                                              *"
echo "****************************************************************"
