#!/bin/bash
set -e
cd "`dirname \"$0\"`/.."

(php -v | grep 'PHP 5.3') || brew install homebrew/php/php53
which composer || brew install homebrew/php/composer


rm -rf ./output/ # clean-up previous generated client directory
./script/swagger


# for node
(cd test/node && npm install swagger-js-codegen)


echo "****************************************************************"
echo "*                                                              *"
echo "*                         Good to go!                          *"
echo "*                                                              *"
echo "****************************************************************"
