#!/bin/bash
set -e
cd "`dirname \"$0\"`/.."

rf -rf ./output/ # clean-up previous generated client directory
./script/swagger


echo "****************************************************************"
echo "*                                                              *"
echo "*                         Good to go!                          *"
echo "*                                                              *"
echo "****************************************************************"