#!/bin/bash
set -e
cd "`dirname \"$0\"`/.."

if [ ! -d "swagger-codegen" ]; then
  git clone https://github.com/swagger-api/swagger-codegen
fi

SWAGGER_CODGEN_REVISION="30228dcca5bb4e5d711071d43077ee074f9970e4"
cd swagger-codegen
git checkout $SWAGGER_CODGEN_REVISION || (git fetch && git checkout $SWAGGER_CODGEN_REVISION)
cd ..

executable="./swagger-codegen/modules/swagger-codegen-cli/target/swagger-codegen-cli.jar"

if [ ! -f "$executable" ]; then
  mvn clean package
fi

export JAVA_OPTS="${JAVA_OPTS} -Xmx1024M -DloggerPath=conf/log4j.properties"
java $JAVA_OPTS -jar $executable $*
